name: Check

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

env:
  HUSKY: 0
  NEXT_PUBLIC_ENVIRONMENT: development
  NEXT_PUBLIC_TRIGGER_PUBLIC_API_KEY: trg_1234567890

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: 'use node ${{ env.node_version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.node_version }}'
      - name: Setup Volta
        uses: volta-cli/action@v4
      - name: Install Dependencies
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Typecheck / Lint / Format
        run: pnpm format
      - name: Unit & Integration tests
        run: pnpm test
      - name: Smoke & Acceptance tests
        run: |
          pnpm build-storybook --quiet
          pnpm playwright install
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && pnpm test-storybook"
