name: Check

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  workflow_dispatch:

env:
  HUSKY: 0
  NODE_VERSION: "20"
  NODE_OPTIONS: '--max-old-space-size=8192'
  NEXT_PUBLIC_ENVIRONMENT: development
  NEXT_PUBLIC_TRIGGER_PUBLIC_API_KEY: trg_1234567890
  KINDE_CLIENT_ID: '1234567890'
  KINDE_CLIENT_SECRET: '1234567890'
  KINDE_ISSUER_URL: 'https://dev-1234567890.okta.com'
  KINDE_SITE_URL: 'https://dev-1234567890.okta.com'
  KINDE_POST_LOGOUT_REDIRECT_URL: 'https://localhost:3030'
  KINDE_POST_LOGIN_REDIRECT_URL: 'https://localhost:3030'

jobs:
  check:
    name: Check
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment Variables
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/set-environment.sh >> $GITHUB_ENV
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Unit tests
        run: pnpm test:unit
