name: 'Next.js Bundle Analysis'

permissions: write-all

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

env:
  HUSKY: 0
  NODE_VERSION: 20
  SKIP_ENV_VALIDATION: true
  NODE_OPTIONS: '--max-old-space-size=8192'
  NEXT_PUBLIC_ENVIRONMENT: development
  NEXT_PUBLIC_TRIGGER_PUBLIC_API_KEY: trg_1234567890
  KINDE_CLIENT_ID: '1234567890'
  KINDE_CLIENT_SECRET: '1234567890'
  KINDE_ISSUER_URL: 'https://dev-1234567890.okta.com'
  KINDE_SITE_URL: 'https://dev-1234567890.okta.com'
  KINDE_POST_LOGOUT_REDIRECT_URL: 'https://localhost:3030'
  KINDE_POST_LOGIN_REDIRECT_URL: 'https://localhost:3030'
  APP_PATH: .

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment Variables
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/set-environment.sh >> $GITHUB_ENV 2>&1
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Restore next build
        uses: actions/cache@v4
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: ${{ env.APP_PATH }}/.next/cache
          # change this if you prefer a more strict cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build next.js app
        # change this if your site requires a custom build command
        run: pnpm build:app
        env:
          SKIP_BUILD_PRODUCT_REDIRECTS: 1

      # Here's the first place where next-bundle-analysis' own script is used
      # This step pulls the raw bundle stats for the current bundle
      - name: Analyze bundle
        run: pnpm tsx report-bundle-size.ts

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ${{ env.APP_PATH }}/.next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v7
        if: success() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml
          path: ${{ env.APP_PATH }}/.next/analyze/base
          branch: ${{ github.event.pull_request.base.ref }}

      # And here's the second place - this runs after we have both the current and
      # base branch bundle stats, and will compare them to determine what changed.
      # There are two configurable arguments that come from package.json:
      #
      # - budget: optional, set a budget (bytes) against which size changes are measured
      #           it's set to 350kb here by default, as informed by the following piece:
      #           https://infrequently.org/2021/03/the-performance-inequality-gap/
      #
      # - red-status-percentage: sets the percent size increase where you get a red
      #                          status indicator, defaults to 20%
      #
      # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
      # entry in your package.json file.
      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Get comment body
        id: get-comment-body
        if: success() && github.event.number
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const comment = fs.readFileSync('${{ env.APP_PATH }}/.next/analyze/__bundle_analysis_comment.txt', 'utf8')
            core.setOutput('body', comment)

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v4
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v4
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
