name: Validate Renovate Config

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Validate Config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
